image: mrcyjanek/goprod:core-linux
env: X=ANDROID COMBO=android/amd64;android/386;android/arm;android/arm64;android/all BINNAME=jwstudy VERSION
matrix:
  - image: mrcyjanek/goprod:core-linux
    env: M=linux-lorca
  - image: mrcyjanek/goprod:core-linux
    env: M=linux-browser
  - image: mrcyjanek/goprod:core-windows
    env: M=windows-lorca
  - image: mrcyjanek/goprod:core-windows
    env: M=windows-browser
  - image: mrcyjanek/goprod:core-android
    env: M=android
script: 
  - make $M
  - cp build/deb/*.deb /apt/ || true
  - cp build/bin/* /archive || true
  - cp build/apk/* /archive || true