image: mrcyjanek/goprod:core-linux
matrix:
  - image: mrcyjanek/goprod:core-linux
    env: M=linux-lorca
  - image: mrcyjanek/goprod:core-linux
    env: M=linux-browser
  - image: mrcyjanek/goprod:core-windows
    env: M=windows-lorca
  - image: mrcyjanek/goprod:core-windows
    env: M=windows-browser
  - image: mrcyjanek/goprod:core-android
    env: M=android
script: 
  - if [[ "$M" == "android" && "$ABSTRUSE_BRANCH" != "master" ]]; then true; else make $M; fi
  - cp build/deb/*.deb /apt/ || true
  - cp build/bin/* /archive || true
  - cp build/apk/* /archive || true