image: mrcyjanek/goprod:latest

matrix:
  - env: TAGS=guibrowser BINNAME=jwstudy-browser
  - env: TAGS=guilorca BINNAME=jwstudy
  - script:
      - goprod -combo="android/arm;android/386;android/arm64;android/amd64" -binname="jwstudy" -version="2.0.0" -ldflags="-X main.dataDir=/data/data/x.x.jwstudy/ -X webui.Port=8080" -tags="nogui" -package=true -appport=8080 
      - cp build/apk/*.apk /archive/
before_script:
  - git config user.email cyjan@mrcyjanek.net
  - git config user.name "Czarek Nakamoto"
  - mkdir -p /usr/share/icons/hicolor/scalable/apps/
script:
  - goprod -combo="linux/amd64" -binname="$BINNAME" -tags="$TAGS" -version="2.0.0"
  - goprod -combo="linux/386" -binname="$BINNAME" -tags="$TAGS" -version="2.0.0"
  - goprod -combo="linux/arm" -binname="$BINNAME" -tags="$TAGS" -version="2.0.0"
  - goprod -combo="linux/arm64" -binname="$BINNAME" -tags="$TAGS" -version="2.0.0"
  - goprod -combo="windows/amd64" -binname="$BINNAME" -tags="$TAGS" -version="2.0.0"
  - goprod -combo="windows/386" -binname="$BINNAME" -tags="$TAGS" -version="2.0.0"
  - cp build/deb/*.deb /apt/
  - cp build/bin/* /archive